### ISSUE TITLE
Giving the module errors during the installation . Not running the requiment modules first

### ISSUE THREAD

**Issue by Rupasinghe2012** [chaturanga50/opsworks-cli#24]
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python2 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3qFwRO/opsworks-cli/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3qFwRO/opsworks-cli/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-3qFwRO/opsworks-cli/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3qFwRO/opsworks-cli/setup.py", line 5, in <module>
        import modules.common_functions
      File "modules/__init__.py", line 1, in <module>
        from modules.execute_recipes import execute_recipes
      File "modules/execute_recipes.py", line 8, in <module>
        import prettytable
    ImportError: No module named prettytable
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by chaturanga50** [comment]
@Rupasinghe2012 tried with both major versions of the python and there is no error coming like this with the installation. Please let me know more information about this.
`Collecting opsworks-cli
  Downloading https://files.pythonhosted.org/packages/93/30/8c95685f137af88463e4a39b932d995ee320323738061575809d6df42617/opsworks-cli-0.5.2.tar.gz
Collecting boto3 (from opsworks-cli)
  Downloading https://files.pythonhosted.org/packages/34/f9/70047ba54fc389ec5e57e60e6b59d9f77d48d5dbd969b0f7ba6e65d33f56/boto3-1.12.27-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 311kB/s 
Collecting prettytable (from opsworks-cli)
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->opsworks-cli)
  Using cached https://files.pythonhosted.org/packages/a3/43/1e939e1fcd87b827fe192d0c9fc25b48c5b3368902bfb913de7754b0dc03/jmespath-0.9.5-py2.py3-none-any.whl
Collecting botocore<1.16.0,>=1.15.27 (from boto3->opsworks-cli)
  Downloading https://files.pythonhosted.org/packages/a1/32/2446ef9e6fb96ce91ed3581027beb858f8918a5fdc27ae283583eef02228/botocore-1.15.27-py2.py3-none-any.whl (6.0MB)
    100% |████████████████████████████████| 6.0MB 328kB/s 
Collecting s3transfer<0.4.0,>=0.3.0 (from boto3->opsworks-cli)
  Using cached https://files.pythonhosted.org/packages/69/79/e6afb3d8b0b4e96cefbdc690f741d7dd24547ff1f94240c997a26fa908d3/s3transfer-0.3.3-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10 (from botocore<1.16.0,>=1.15.27->boto3->opsworks-cli)
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.16.0,>=1.15.27->boto3->opsworks-cli)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting urllib3<1.26,>=1.20; python_version != "3.4" (from botocore<1.16.0,>=1.15.27->boto3->opsworks-cli)
  Using cached https://files.pythonhosted.org/packages/e8/74/6e4f91745020f967d09332bb2b8b9b10090957334692eb88ea4afe91b77f/urllib3-1.25.8-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore<1.16.0,>=1.15.27->boto3->opsworks-cli)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Building wheels for collected packages: opsworks-cli
  Running setup.py bdist_wheel for opsworks-cli ... done
  Stored in directory: /home/chathuranga/.cache/pip/wheels/ab/45/e0/5b31f576202961afc795f7d89ca3d5919f69a1c1cd7be7962d
Successfully built opsworks-cli
Installing collected packages: jmespath, docutils, six, python-dateutil, urllib3, botocore, s3transfer, boto3, prettytable, opsworks-cli
Successfully installed boto3-1.12.27 botocore-1.15.27 docutils-0.15.2 jmespath-0.9.5 opsworks-cli-0.5.2 prettytable-0.7.2 python-dateutil-2.8.1 s3transfer-0.3.3 six-1.14.0 urllib3-1.25.8
`

**Comment by chaturanga50** [comment]
closing due to inactivity
