### ISSUE TITLE
running with both layerid and custom json throwing  error

### ISSUE THREAD

**Issue by chaturanga50** [chaturanga50/opsworks-cli#3]
`Traceback (most recent call last):
  File "/usr/local/bin/opsworks-cli", line 14, in <module>
    modules.execute_recipes()    
  File "/usr/local/lib/python2.7/site-packages/modules/execute_recipes.py", line 46, in execute_recipes
    get_names(stack, layer, region, "execute_recipe")
  File "/usr/local/lib/python2.7/site-packages/modules/common_functions.py", line 117, in get_names
    layer,
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/usr/local/lib/python2.7/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter LayerIds[0], value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>`

**Comment by chaturanga50** [comment]
#4 merging the fix with master
